feat: move policy code to publish
chanzuckerberg/single-cell-data-portal pull request #1575
Opened 2021-10-22 20:55 UTC by dimple-jethani

### Reviewers

**Functional:** 
@MDunitz @tihuan 

**Readability:** 
@Bento007 

---

## Changes
https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/1336

Moving policy code from create collection modal to publish modal. We're removing `data_submission_policy_version` from being stored after the create modal and instead it's being stored once a collection is published/revised.

data_submission_policy_version being stored correctly after publishing a dataset and a revision:
![Screen Shot 2021-10-22 at 11 15 08 AM](https://user-images.githubusercontent.com/55212249/138503547-856ef87d-fd8b-4ee7-8ba4-b80aadfa082c.png)

## Definition of Done (from ticket)
1. Add policy confirmation check at publish time, according to the Figma - Done
2. Remove policy check when creating and editing collection metadata - Done
3. Update E2E tests (revisions.ts) to work with the updated revision flow - still WIP

2021-11-01 17:21 UTC, seve commented
I'll be taking over this PR, looks like some more backend unit tests need to be tweaked.

2021-11-10 00:30 UTC, Bento007 requested changes

2021-11-15 19:38 UTC, Bento007 approved these changes

2021-11-15 21:05 UTC, tihuan commented on frontend/src/common/queries/collections.ts
> +export type PublishCollection = {
@seve does this look good to you? Thanks!

2021-11-15 22:58 UTC, merged