feat: add dataset_preview schema
chanzuckerberg/single-cell-data-portal pull request #1981
Opened 2022-02-18 02:42 UTC by danieljhegeman

### Reviewers
**Functional:** 
@Bento007 
**Readability:** 

---

## Changes
- add
- remove
- modify

## Definition of Done (from ticket)

## QA steps (optional)

## Known Issues

2022-02-18 16:25 UTC, Bento007 requested changes
What Endpoint with these be used?

2022-02-18 16:25 UTC, Bento007 commented on backend/open_api_spec.yml
> +      required:
These are all fields in a response. You don't need required.

2022-02-18 16:25 UTC, Bento007 commented on backend/open_api_spec.yml
> +      required:
This is only a response, you don't need required.

2022-04-15 07:47 UTC, danieljhegeman commented
outdated

2022-04-15 07:47 UTC, closed without merging