chore: move wmg api endpoints to separate api spec file
chanzuckerberg/single-cell-data-portal pull request #2202
Opened 2022-03-25 21:27 UTC by atolopko-czi

- move wmg endpoints to wmg-api.config file, out of corpora-api.config

- upgrade connexion to latest version & update connexion usage as needed for
multi-api support

- add in top-level index.html page for navigating to each of the independent
api's swagger UI pages

- move data portal API's swagger UI to /dp base path; this also allows us to
remove /dp prefix from each endpoint in the spec file.

### Reviewers
**Functional:** 

**Readability:** 

---

## Changes
- add
- remove
- modify

## Definition of Done (from ticket)

## QA steps (optional)

## Known Issues

2022-03-26 01:48 UTC, atolopko-czi commented on tests/unit/backend/corpora/api_server/test_revisions.py
> +    def verify_datasets(self, actual_body: dict, expected_dataset_ids: typing.Set[str]) -> None:
unrelated fix for transient test failures

2022-04-01 16:24 UTC, MDunitz approved these changes
lgtm

2022-04-01 19:14 UTC, Bento007 requested changes
missed some stuff

2022-04-01 19:14 UTC, Bento007 commented on backend/config/wmg-api.yml
> +  /wmg/v1/primary_filter_dimensions:
remove wmg
```suggestion
  /v1/primary_filter_dimensions:
```

2022-04-01 19:14 UTC, Bento007 commented on backend/config/wmg-api.yml
> +  /wmg/v1/query:
```suggestion
  /v1/query:
```

2022-04-01 19:14 UTC, Bento007 commented on tests/unit/backend/corpora/api_server/base_api_test.py
> +    Provide access to the test APIs. All tests for APIs should inherit this class.
:+1:

2022-04-19 18:59 UTC, merged