Tsmith/2149 post collection
chanzuckerberg/single-cell-data-portal pull request #2520
Opened 2022-05-10 16:45 UTC by Bento007

### Reviewers
**Functional:** 

**Readability:** 

---

## Changes
- add post collection route
- add put collection route
- add post revision route
- add upload from link route

## Definition of Done (from ticket)

## QA steps (optional)

## Known Issues

2022-05-20 20:03 UTC, metakuni approved these changes

2022-05-20 20:03 UTC, metakuni commented on backend/corpora/lambdas/api/v1/collection.py
>  def create_collection(body: object, user: str):
Not part of this PR, but:
```suggestion
def create_collection(body: dict, user: str):
```

2022-05-25 08:26 UTC, danieljhegeman requested changes
Shape of error response for links needs to conform to the spec

2022-05-25 18:36 UTC, danieljhegeman approved these changes
🚀

2022-05-25 19:09 UTC, merged