Update DataSubmission Lambda
chanzuckerberg/single-cell-data-portal pull request #2565
Opened 2022-05-19 22:46 UTC by Bento007

- #TICKET_NUMBER

### Reviewers
**Functional:** 

**Readability:** 

---

## Changes
- Modify the expected format of the s3 object. Object must now conform to one of the following shapes:
  - S3://{bucket}/{user}/{collection}/id/{dataset}.h5ad or
  - S3://{bucket}/{user}/{collection}/tag/{tag}.h5ad

## QA steps (optional)

## Notes for Reviewer

2022-05-19 22:59 UTC, metakuni approved these changes

2022-05-19 22:59 UTC, metakuni commented on backend/corpora/dataset_submissions/app.py
> +EXTENTION_REGEX = r"(?P<extension>h5ad)"
```suggestion
EXTENSION_REGEX = r"(?P<extension>h5ad)"
```

2022-05-19 22:59 UTC, metakuni commented on backend/corpora/dataset_submissions/app.py
> +REGEX = f"^{USERNAME_REGEX}/{COLLECTION_ID_REGEX}/((tag/(?P<tag>.*))|(id/{DATASET_ID_REGEX})).{EXTENTION_REGEX}$"
```suggestion
REGEX = f"^{USERNAME_REGEX}/{COLLECTION_ID_REGEX}/((tag/(?P<tag>.*))|(id/{DATASET_ID_REGEX})).{EXTENSION_REGEX}$"
```

2022-05-20 02:46 UTC, danieljhegeman commented
This needs to be changed to expect `<bucket>/<collection_id>/<tag_or_dataset_id>` where `<tag_or_dataset_id>` is treated as an id (i.e., it is _necessarily_ replacing an existing dataset) if it conforms to uuid format and as a tag if it does not.

https://czi-sci.slack.com/archives/C02UGUV5R3J/p1652995597685589

2022-05-20 02:47 UTC, danieljhegeman requested changes
See the discussion about removing `/id/` and `/tag/` from the key, and instead relying on interpretation of the "tag" portion.

2022-05-20 19:34 UTC, Bento007 commented
@danieljhegeman [resolved](https://czi-sci.slack.com/archives/C02UGUV5R3J/p1652995597685589)

2022-05-20 21:17 UTC, metakuni approved these changes

2022-05-20 21:17 UTC, metakuni commented on tests/unit/backend/corpora/lambdas/dataset_submissions/test_dataset_submissions.py
>      def test__misssing_extension__raise_error(self):
```suggestion
    def test__missing_extension__raise_error(self):
```

2022-05-20 21:17 UTC, metakuni commented on tests/unit/backend/corpora/lambdas/dataset_submissions/test_dataset_submissions.py
> +        self._test_missing_fields(key=f"{self.user_name}/should_have_been_a_uuid/t{self.incoming_curator_tag}")
```suggestion
        self._test_missing_fields(key=f"{self.user_name}/should_have_been_a_uuid/{self.incoming_curator_tag}")
```

2022-05-22 01:34 UTC, danieljhegeman commented on backend/corpora/dataset_submissions/app.py
> +USERNAME_REGEX = r"(?P<username>[\w\-\|]+)"
cooool 🧊 

I did not know about 'named capture groups' in python. Glad to be introduced. 🧠

2022-05-22 01:36 UTC, danieljhegeman commented on backend/corpora/dataset_submissions/app.py
> +REGEX = f"^{USERNAME_REGEX}/{COLLECTION_ID_REGEX}/((?P<tag>.*)|{DATASET_ID_REGEX}).{EXTENSION_REGEX}$"
gorgeous 🤩

2022-05-22 01:42 UTC, danieljhegeman commented on backend/corpora/dataset_submissions/app.py
> +REGEX = f"^{USERNAME_REGEX}/{COLLECTION_ID_REGEX}/((?P<tag>.*)|{DATASET_ID_REGEX}).{EXTENSION_REGEX}$"
But one problem. suggested fix:

```suggestion
REGEX = f"^{USERNAME_REGEX}/{COLLECTION_ID_REGEX}/((?P<tag>.*)|{DATASET_ID_REGEX})\\.{EXTENSION_REGEX}$"
```

2022-05-22 02:10 UTC, danieljhegeman commented on backend/corpora/dataset_submissions/app.py
> +    s3://<dataset submissions bucket>/<user_id>/<collection_id>/<dataset_id>
```suggestion
    Example of key with only curator_tag:
    s3://<dataset submissions bucket>/<user_id>/<collection_id>/<curator_tag.h5ad>

    Example of key with dataset id:
    s3://<dataset submissions bucket>/<user_id>/<collection_id>/<dataset_id.h5ad>
```

2022-05-24 23:10 UTC, Bento007 commented on backend/corpora/dataset_submissions/app.py
> +REGEX = f"^{USERNAME_REGEX}/{COLLECTION_ID_REGEX}/((?P<tag>.*)|{DATASET_ID_REGEX}).{EXTENSION_REGEX}$"
I thought I fixed that. Good catch.

2022-05-24 23:52 UTC, danieljhegeman approved these changes
I think we're good!

2022-05-31 21:07 UTC, merged