docs: Renaming scExpression to Gene Expression
chanzuckerberg/single-cell-data-portal pull request #3091
Opened 2022-08-11 19:52 UTC by ashin-czi

- #3030 

### Reviewers
**Functional:** @seve @pablo-gar

**Readability:** @seve @pablo-gar 

---

## Changes
- add
- remove
- modify
    - Nav bar scExpression to Gene Expression
    - scExpression text in docs to Gene Expression

## QA steps (optional)

## Notes for Reviewer

2022-08-12 17:38 UTC, seve requested changes
We should probably change the name of the pages themselves too

2022-08-16 15:34 UTC, ashin-czi commented
> We should probably change the name of the pages themselves too

@seve Do you mean changing the URL? Like:
https://cellxgene.cziscience.com/scExpression => https://cellxgene.cziscience.com/GeneExpression

2022-08-25 17:01 UTC, seve approved these changes

2022-08-25 17:47 UTC, merged

2022-08-30 17:47 UTC, ashin-czi commented
Ready for staging