feat: Removing right sidebar and moving legend out
chanzuckerberg/single-cell-data-portal pull request #3220
Opened 2022-09-01 16:50 UTC by ashin-czi

- #3174

### Reviewers
**Functional:** @seve

**Readability:** @seve 

---

## Changes
- add 
    - Legend in top nav bar
- remove 
    - Right sidebar
- modify

## QA steps (optional)

## Notes for Reviewer

2022-09-01 18:04 UTC, ashin-czi commented
@hthomas-czi 

Are we removing the scaled checkbox in scExpression? I didn't see it on Figma
<img width="104" alt="image" src="https://user-images.githubusercontent.com/109984998/187982744-83ee13cd-8dcd-4fe7-8030-2fe41b7dc92a.png">

2022-09-07 18:31 UTC, seve commented
@ashin-czi 
> Are we removing the scaled checkbox in scExpression? I didn't see it on [Figma](https://www.figma.com/file/JS5ThqTBcpAVuBFglAItKf/Gene-Search?node-id=3526%3A591388) so was wondering if we're still supporting it <img alt="image" width="104" src="https://user-images.githubusercontent.com/109984998/187982744-83ee13cd-8dcd-4fe7-8030-2fe41b7dc92a.png">

Scale is moving from the right sidebar as a checkbox to the left sidebar as a dropdown.
<img width="289" alt="image" src="https://user-images.githubusercontent.com/8716829/188952231-0103b2d2-8533-43e9-81a8-c248fc7b0fac.png">

2022-09-07 18:38 UTC, seve requested changes

2022-09-07 18:38 UTC, seve commented on frontend/src/views/WheresMyGene/components/Beta/index.tsx
> +      onClose={function () {}}
we have a noop util somewhere that we use as a stand in for this

2022-09-07 18:38 UTC, seve commented on frontend/src/views/WheresMyGene/components/Beta/index.tsx
> +        submit an issue on our GitHub
We should either leave this with the survey copy or switch the link. 
cc: @hthomas-czi

2022-09-12 22:02 UTC, seve approved these changes

2022-09-14 17:16 UTC, merged