feature: Gene Expression Right Sidebar Changes
chanzuckerberg/single-cell-data-portal pull request #3365
Opened 2022-09-29 19:21 UTC by ashin-czi

- #3364

### Reviewers
**Functional:** @seve 

**Readability:** @seve 

---

## Changes
- add
- remove
- modify
    - Creating button to open right sidebar for source data and methodology
    - Moving download button

## QA steps (optional)

## Notes for Reviewer

2022-10-04 18:43 UTC, ashin-czi commented
Here's a recording of how the changes look

https://user-images.githubusercontent.com/109984998/193900403-4cb9d59d-b606-46d5-b386-04186b3463ca.mov

2022-10-04 19:23 UTC, seve requested changes

2022-10-04 19:23 UTC, seve commented on frontend/src/views/WheresMyGene/components/GeneSearchBar/components/SourceDataButton/index.tsx
> +    <StyledButtonDiv>
throw the "exclude from screenshot" class on this

2022-10-05 21:34 UTC, seve requested changes
a couple of nits, then we're good

2022-10-05 21:34 UTC, seve commented on frontend/src/views/WheresMyGene/components/GeneSearchBar/components/SaveImage/index.tsx
> +      >
Can we use `.styled` instead of style prop

2022-10-05 21:34 UTC, seve commented on frontend/src/views/WheresMyGene/components/GeneSearchBar/components/SourceDataButton/index.tsx
> +    <StyledButtonDiv className="screenshot-exclude">
use the constant instead of hardcoded

2022-10-06 18:11 UTC, seve approved these changes

2022-10-07 20:09 UTC, merged