fix(fmg): fix ordering and remove p-value
chanzuckerberg/single-cell-data-portal pull request #3831
Opened 2022-12-22 22:34 UTC by seve

- #3801 #3804 

### Reviewers
**Functional:** @tihuan @atarashansky 

Changed backend repsonse shape to have `marker_genes` be an array to preserve ordering
Removed p-values from table

2022-12-22 22:36 UTC, seve commented on backend/wmg/api/wmg-api.yml
> -                    additionalProperties:
GitHub's formatting on this diff is attrotious, sorry

2022-12-22 22:37 UTC, seve commented on backend/wmg/api/wmg-api.yml
> -                          maximum: 1.0
Oops this should still be here, fixing

2023-01-03 14:00 UTC, atarashansky requested changes
Looks good, but I think unit tests need to be updated to expect the new response format (a list instead of a dictionary).

`QueryTest.test__query_marker_genes_cube__returns_correct_top_10_markers`
`QueryTest.test__query_marker_genes_cube__returns_correct_all_markers`
`MarkerGeneCalculationTest.test__get_markers_ttest`
`MarkerGeneCalculationTest.test__get_markers_binomtest`
`WmgApiV1Tests.test__markers_returns_200_and_correct_response`
`WmgApiV1Tests.test__markers_returns_200_and_empty_dictionary_for_bad_celltypes`

2023-01-03 21:21 UTC, seve commented on frontend/src/views/WheresMyGene/components/CellInfoSideBar/index.tsx
> -          <CellHeader hideSortIcon horizontalAlign="right">
since they're already in git history I'm going to leave them as deleted

2023-01-04 15:33 UTC, atarashansky requested changes
Hey @seve - the tests are running now. PTAL, I think there are a couple of minor issues (like using assertDictEquals to compare lists - for lists, you can use assertEqual).

EDIT: I went ahead and fixed it - very minor changes required!

2023-01-04 18:21 UTC, merged