chore: move some tests to portal redesign
chanzuckerberg/single-cell-data-portal pull request #3892
Opened 2023-01-09 20:59 UTC by ebezzi

Move tests to the `layers` folder as part of the redesign. This PR is a work in progress.

2023-01-09 21:00 UTC, ebezzi commented on backend/layers/processing/upload_failures/app.py
> +        get_business_logic().update_dataset_version_status(
Easier to use this function now, especially since base tests already mock it.

2023-01-10 23:34 UTC, Bento007 requested changes

2023-01-10 23:34 UTC, Bento007 commented on tests/unit/backend/common/utils/dl_sources/test_url.py
> -from backend.common.utils.dl_sources.url import from_url, RegisteredSources, S3URL, DropBoxURL, S3URI
This code is still used in url_provider.py, the test should be updated rather than deleted

2023-01-30 15:12 UTC, nayib-jose-gloria commented on backend/layers/processing/upload_failures/app.py
> +from backend.layers.api.providers import get_business_logic
after the API layer refactor, this is at `backend.portal.api.providers` now

2023-01-30 21:16 UTC, nayib-jose-gloria approved these changes

2023-01-30 22:21 UTC, Bento007 approved these changes

2023-01-31 00:15 UTC, merged