refactor(portal redesign): delete deprecated API files and reorganize directory
chanzuckerberg/single-cell-data-portal pull request #3916
Opened 2023-01-11 18:22 UTC by nayib-jose-gloria

Signed-off-by: nayib-jose-gloria <ngloria@chanzuckerberg.com>

- #3669

### Reviewers
**Functional:** 

**Readability:** 

---

## Changes
- delete portal API files + associated tests that are no longer in use (use previous, non-versioned data model)
- move portal + curation API-level directories to top of backend directory, to match other APIs (i.e. wmg, gene_info)

## QA steps (optional)
- tests

## Notes for Reviewer

2023-01-11 21:25 UTC, Bento007 requested changes
- move curation/v1 -> curation/api/v1

2023-01-19 16:49 UTC, nayib-jose-gloria reviewed
someone else should give final approval since I pushed to this branch, but latest commits look good and it works in rdev!

2023-01-20 23:59 UTC, Bento007 approved these changes

2023-01-23 19:01 UTC, ebezzi approved these changes

2023-01-23 19:08 UTC, merged