feat(wmg): Hide marker genes with marker score <0.5
chanzuckerberg/single-cell-data-portal pull request #4248
Opened 2023-02-22 22:12 UTC by ashin-czi

## Reason for Change

- #4228 
- If the reason for this PR's code changes are not clear in the issue, state value/impact

## Changes

- add
    - New view in FMG panel for when no reliable marker genes are found
    - removing genes <0.5 from marker genes panel
    - limiting marker genes shown to top 25 genes
- remove
- modify

## Testing steps

- Either list QA steps or reasoning you feel QA is unnecessary
- Describe how you made sure to know that your changes worked. Should allow someone else to go verify your code without in depth knowledge.
- "Unit tested only", "tested in rdev by a, b, c, verifying feature worked by... ", "manually ran pipeline locally with these results: ..."

## Notes for Reviewer

2023-02-24 16:37 UTC, atarashansky requested changes
Great job, @ashin-czi! Looks good. Just one comment about the gene count limit constant you added - we can safely get rid of that and all references to it.

2023-02-24 16:37 UTC, atarashansky commented on frontend/src/views/WheresMyGene/common/constants.ts
> +export const FMG_GENE_COUNT_LIMIT = 25;
Good thinking, but the gene count limit is determined as a parameter sent via the request body to the marker genes endpoint. So this is not necessary and duplicating logic.

TL;DR - you can get rid of this and don't need to `.slice(0,FMG_GENE_COUNT_LIMIT)`

2023-02-24 16:37 UTC, atarashansky commented on frontend/src/common/queries/wheresMyGene.ts
> +      .slice(0, FMG_GENE_COUNT_LIMIT);
see previous comment - you can safely get rid of this <3

2023-02-24 22:38 UTC, ashin-czi commented
Waiting on analytics: https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-data-portal/4259

2023-03-07 17:03 UTC, tihuan commented
@ashin-czi is this PR ready for review? Just wanted to see if the double event thing was resolved yesterday 🤞 Thank you!

2023-03-07 17:44 UTC, ashin-czi commented
@tihuan Yes it is!

2023-03-07 17:50 UTC, atarashansky approved these changes
looks great!

2023-03-07 17:50 UTC, atarashansky commented on frontend/src/common/queries/wheresMyGene.ts
> +}: FetchMarkerGeneParams): UseQueryResult<MarkerGeneResponse<MarkerGene>> {
just curious - why was parametrizing `MarkerGene` like this necessary?

2023-03-07 17:50 UTC, atarashansky commented on frontend/src/common/queries/wheresMyGene.ts
> +          [] as [string, Partial<MarkerGene>][]
TIL `Partial` is a thing. This answers my previous question.

2023-03-07 17:52 UTC, merged