Cchoi/publication filter
chanzuckerberg/single-cell-data-portal pull request #4965
Opened 2023-06-06 18:51 UTC by carolinechoi

## Reason for Change

- #TICKET_NUMBER
- If the reason for this PR's code changes are not clear in the issue, state value/impact

## Changes

- add
- remove
- modify

## Testing steps

- Either list QA steps or reasoning you feel QA is unnecessary
- Describe how you made sure to know that your changes worked. Should allow someone else to go verify your code without in depth knowledge.
- "Unit tested only", "tested in rdev by a, b, c, verifying feature worked by... ", "manually ran pipeline locally with these results: ..."

## Notes for Reviewer

2023-06-14 19:36 UTC, seve requested changes

2023-06-14 19:36 UTC, seve commented on frontend/src/views/WheresMyGene/components/Filters/index.tsx
> +  id: string | string[];
Since we're not doing "No publications" we can probably drop the `string[]`

2023-06-14 19:36 UTC, seve commented on frontend/src/views/WheresMyGene/components/Filters/index.tsx
> +        {/* CAROLINE U ARE HERE  */}
```suggestion
```

2023-06-14 19:38 UTC, seve requested changes

2023-06-14 19:38 UTC, seve commented on .happy/config.json
i would drop this file from your PR since you aren't actually changing anything other than formatting

2023-06-14 19:38 UTC, seve commented on package.json
looks like you ran `npm install prettier` in the wrong directory

2023-06-14 20:24 UTC, carolinechoi commented on package.json
poop

2023-06-14 20:27 UTC, carolinechoi commented on frontend/src/common/queries/wheresMyGene.ts
> +  const { mode, status } = useViewMode();
Should I just set it to the default mode/status then? I need something to pass through useFetchCollectionRows on line 455.

2023-06-15 20:15 UTC, seve approved these changes

2023-06-15 20:42 UTC, merged