feat: add sqsum array to expression summary default cube [WIP]
chanzuckerberg/single-cell-data-portal pull request #5184
Opened 2023-07-10 18:24 UTC by joyceyan

## Reason for Change

first component of this ticket: https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-data-portal/5093

this PR adds the `sqsum` array to the expression summary default cube. up next:
- actually read from it in `calculate_markers`
- deprecate `expression_summary_fmg`

this PR also includes some aesthetic code changes, such as:
1. ensuring we have the return type annotated on every function i touched
2. adding the `*` decorator to all functions i touched, which requires callers to name the params. this helps ensure that you don't end up touching the wrong parameter just because you ordered something wrong
3. created Result class objects rather than returning tuples. i think having a typed result object is a lot easier to read when you're returning more than two things. similarly, this helps prevent the caller of the function from setting one of the result values to be the wrong thing if you just ordered your variables wrong

## Testing steps

re-generated realistic test snapshots

## Notes for Reviewer

2023-07-10 18:25 UTC, joyceyan commented on backend/wmg/pipeline/summary_cubes/expression_summary_fmg/job.py
> -) -> (list, dict):
we're not actually returning anything here, so i updated this to `None`

2023-07-25 13:25 UTC, atarashansky requested changes

2023-07-25 13:25 UTC, atarashansky commented on backend/wmg/pipeline/summary_cubes/expression_summary/job.py
> +        result = transform(corpus_path, gene_ontology_term_ids, cube_dims)
I think the args here need to be keyword arguments. The pipeline failed with an error indicating as such:
https://us-west-2.console.aws.amazon.com/cloudwatch/home?region=us-west-2#logsV2:log-groups/log-group/%2Fdp%2Frdev%2Fstack-name%2Fwmg-processing/log-events/wmg-rdev-stack-name-wmg-processing%2Fdefault%2F1bd4a7129c9d4943a9881f7974f6389b

2023-08-02 15:09 UTC, joyceyan commented
closing to open a new PR with rdev stack

2023-08-02 15:09 UTC, closed without merging