chore(cellguide): Minor UI fixes – #5410
chanzuckerberg/single-cell-data-portal pull request #5431
Opened 2023-08-10 16:35 UTC by ashin-czi

## Reason for Change

- #5410 

## Changes

- add
- remove
- modify

## Testing steps

- Either list QA steps or reasoning you feel QA is unnecessary
- Describe how you made sure to know that your changes worked. Should allow someone else to go verify your code without in depth knowledge.
- "Unit tested only", "tested in rdev by a, b, c, verifying feature worked by... ", "manually ran pipeline locally with these results: ..."

## Notes for Reviewer

2023-08-10 18:02 UTC, hthomas-czi requested changes
Looks good! I just noticed one small missing change for `fontHeader.xl`

2023-08-16 18:49 UTC, atarashansky requested changes
The changes in scope for the attached ticket looks good, but can I ask for your help fixing this minor UI bug? (see attached video)

https://github.com/chanzuckerberg/single-cell-data-portal/assets/16548075/60bb30a4-c5a6-4e9f-b694-0ca0e5426ade

2023-08-16 20:05 UTC, atarashansky approved these changes

2023-08-16 20:21 UTC, hthomas-czi commented on frontend/src/common/theme.ts
>        xl: {
Could we actually keep `fontSize: 24px` and `lineHeight: 32px` for `header.xl`?

2023-08-16 20:23 UTC, hthomas-czi commented on frontend/src/common/theme.ts
>        xxl: {
Could we increase `header.xxl` to `fontSize: 32px` and `lineHeight: 36px`?

I'd like to do this instead of making `header.xl` smaller.

2023-08-16 20:25 UTC, hthomas-czi requested changes
Hi Andrew! I requested two changes to the text styles in the theme file. Sorry to change it on you. Let me know if it's too late to adjust. 

Otherwise it looks good to me!

2023-08-17 18:08 UTC, hthomas-czi approved these changes
Looks great!

2023-08-18 18:19 UTC, merged