feat: heatmap divider
chanzuckerberg/single-cell-data-portal pull request #5688
Opened 2023-09-01 21:28 UTC by tihuan

## Reason for Change

- #TICKET_NUMBER
- If the reason for this PR's code changes are not clear in the issue, state value/impact

## Changes

1. Add divider

![Uploading Screenshot 2023-09-01 at 2.26.16 PM.png…]()

## Testing steps

- Either list QA steps or reasoning you feel QA is unnecessary
- Describe how you made sure to know that your changes worked. Should allow someone else to go verify your code without in depth knowledge.
- "Unit tested only", "tested in rdev by a, b, c, verifying feature worked by... ", "manually ran pipeline locally with these results: ..."

## Notes for Reviewer

2023-09-01 21:30 UTC, tihuan commented on frontend/src/views/WheresMyGeneV2/components/HeatMap/style.ts
> +enum ZIndex {
Add enum to manage z-index order

2023-09-01 21:30 UTC, tihuan commented on frontend/src/views/WheresMyGeneV2/components/HeatMap/style.ts
> +export const XAxisWrapper = styled.div`
copied from the old file

2023-09-01 21:30 UTC, tihuan commented on frontend/src/views/WheresMyGeneV2/components/HeatMap/style.ts
> +`;
copied from the old file

2023-09-01 22:06 UTC, seve approved these changes

2023-09-05 15:50 UTC, seve requested changes
looks like some commits from main were merged into this branch

2023-09-05 17:29 UTC, tihuan commented
@seve I see that your branch is merged in `main`, so I just cherrypicked my commit on top of `main`!

2023-09-05 18:22 UTC, atarashansky approved these changes

2023-09-05 18:39 UTC, merged