feat: Update “download datasets” copy URL (#5589)
chanzuckerberg/single-cell-data-portal pull request #5835
Opened 2023-09-26 23:51 UTC by frano-m

## Reason for Change

- #5589

## Changes
- Modified download datasets copy URL.

2023-09-27 06:13 UTC, danieljhegeman commented on frontend/src/components/Collections/components/Dataset/components/DownloadDataset/components/Content/index.tsx
@frano-m can you give me context on what these js changes are doing?

2023-09-27 06:20 UTC, danieljhegeman reviewed
@frano-m I'm not seeing where the changes are being introduced that replace a presigned url download link with a `https://datasets.cellxgene.cziscience.com/<dataset_version_id>.<ext>` link, per #5589

2023-09-27 06:24 UTC, danieljhegeman commented
My cursory assessment is that the FE is still calling [this endpoint](https://github.com/chanzuckerberg/single-cell-data-portal/blob/505d9d362f7cec5851eb4793b117f85e95933188/backend/portal/api/portal-api.yml#L549) which (still) generates a presigned url.

2023-09-27 06:26 UTC, danieljhegeman requested changes
See comments

2023-09-27 14:12 UTC, MillenniumFalconMechanic commented
> My cursory assessment is that the FE is still calling [this endpoint](https://github.com/chanzuckerberg/single-cell-data-portal/blob/505d9d362f7cec5851eb4793b117f85e95933188/backend/portal/api/portal-api.yml#L549) which (still) generates a presigned url.
> 
> Copying from #5589:
> 
> > Currently, a request is sent to create and retrieve a pre-signed URL. The generated pre-signed URL is no longer required; the URL is to be assembled by the frontend from the dataset version ID.

Hi @danieljhegeman, we changed the approach on how the permanent URL should be generated but it looks like I didn't update the "need" section of the corresponding ticket. I have just made that update. 

The update to call the new endpoint is [here](https://github.com/chanzuckerberg/single-cell-data-portal/pull/5835/files#diff-fad645b29fca0b75699eff24024074dee4b587f47fbbc95355b6e0558e3137beR74).

The existing POST endpoint will be cleaned up in [this ticket](https://github.com/chanzuckerberg/single-cell-data-portal/issues/5697).

2023-09-27 15:32 UTC, tihuan approved these changes
LGTM 😄 👍 !

2023-09-27 21:33 UTC, danieljhegeman commented on frontend/src/components/Collections/components/Dataset/components/DownloadDataset/components/Content/index.tsx
> +            method: "GET",
I don't think so... I think we want to move away from the presigned s3 url and toward using the Discover API permalink for a given Dataset version.

2023-09-27 21:34 UTC, danieljhegeman commented
> The update to call the new endpoint is [here](https://github.com/chanzuckerberg/single-cell-data-portal/pull/5835/files#diff-fad645b29fca0b75699eff24024074dee4b587f47fbbc95355b6e0558e3137beR74).

This is not a new endpoint, as you allude to in a subsequent comment. It is the same endpoint, just a different method, right?

2023-09-27 21:36 UTC, danieljhegeman commented
> Hi @danieljhegeman, we changed the approach on how the permanent URL should be generated but it looks like I didn't update the "need" section of the corresponding ticket. I have just made that update.

Can you say a bit more about this?

2023-09-28 04:16 UTC, MillenniumFalconMechanic commented
> > The update to call the new endpoint is [here](https://github.com/chanzuckerberg/single-cell-data-portal/pull/5835/files#diff-fad645b29fca0b75699eff24024074dee4b587f47fbbc95355b6e0558e3137beR74).
> 
> This is not a new endpoint, as you allude to in a subsequent comment. It is the same endpoint, just a different method, right?

Ah, I see! Yes, we added a `GET` method to `/datasets/datasetId/asset/assetId` in [this PR](https://github.com/chanzuckerberg/single-cell-data-portal/pull/5794), specifically [here](https://github.com/chanzuckerberg/single-cell-data-portal/blob/main/backend/portal/api/portal-api.yml#L550). 

The existing `POST` method (e.g. [here](https://github.com/chanzuckerberg/single-cell-data-portal/blob/main/backend/portal/api/portal-api.yml#L584)) will be removed with [Remove Data Portal pre-signed asset URL capability](https://github.com/chanzuckerberg/single-cell-data-portal/issues/5697) once this PR lands.

> Can you say a bit more about this?

Originally the approach was to generate the link to the permanent URL on the FE and deprecate the existing `POST` method. During our weekly call on September 13, (@frano-m and) I raised the issue that we need to display a file size in the download modal which is currently provided to the FE via the soon-to-be-deprecated `POST` endpoint. @ebezzi suggested we create a new `GET` method to return both the permanent URL (as we could then re-use the logic used by the curator API) and the file size.

@danieljhegeman, let me know if this isn't clear or if you have any more q's!

2023-09-28 07:53 UTC, danieljhegeman commented
> > > The update to call the new endpoint is [here](https://github.com/chanzuckerberg/single-cell-data-portal/pull/5835/files#diff-fad645b29fca0b75699eff24024074dee4b587f47fbbc95355b6e0558e3137beR74).
> > 
> > 
> > This is not a new endpoint, as you allude to in a subsequent comment. It is the same endpoint, just a different method, right?
> 
> Ah, I see! Yes, we added a `GET` method to `/datasets/datasetId/asset/assetId` in [this PR](https://github.com/chanzuckerberg/single-cell-data-portal/pull/5794), specifically [here](https://github.com/chanzuckerberg/single-cell-data-portal/blob/main/backend/portal/api/portal-api.yml#L550).
> 
> The existing `POST` method (e.g. [here](https://github.com/chanzuckerberg/single-cell-data-portal/blob/main/backend/portal/api/portal-api.yml#L584)) will be removed with [Remove Data Portal pre-signed asset URL capability](https://github.com/chanzuckerberg/single-cell-data-portal/issues/5697) once this PR lands.
> 
> > Can you say a bit more about this?
> 
> Originally the approach was to generate the link to the permanent URL on the FE and deprecate the existing `POST` method. During our weekly call on September 13, (@frano-m and) I raised the issue that we need to display a file size in the download modal which is currently provided to the FE via the soon-to-be-deprecated `POST` endpoint. @ebezzi suggested we create a new `GET` method to return both the permanent URL (as we could then re-use the logic used by the curator API) and the file size.
> 
> @danieljhegeman, let me know if this isn't clear or if you have any more q's!

Thanks @MillenniumFalconMechanic . I think this work just came in / is coming in more piecemeal than I might've expected, but all the same in terms of the end goal. Thanks for confirming!

2023-09-28 07:54 UTC, danieljhegeman approved these changes
📈

2023-10-09 18:01 UTC, tihuan approved these changes

2023-11-03 02:26 UTC, merged