feat(cellguide): authenticated endpoint for uploads
chanzuckerberg/single-cell-data-portal pull request #6289
Opened 2023-11-30 22:38 UTC by kaloster

## Reason for Change

- #TICKET_NUMBER
- If the reason for this PR's code changes are not clear in the issue, state value/impact

## Changes

- add
- remove
- modify

## Testing steps

- Either list QA steps or reasoning you feel QA is unnecessary
- Describe how you made sure to know that your changes worked. Should allow someone else to go verify your code without in depth knowledge.
- "Unit tested only", "tested in rdev by a, b, c, verifying feature worked by... ", "manually ran pipeline locally with these results: ..."

## Checklist 🛎️

- [ ] Add product, design, and eng as reviewers for rdev review
- [ ] For UI changes, add screenshots/videos, so the reviewers know what you expect them to see
- [ ] For UI changes, add e2e tests to prevent regressions

## Notes for Reviewer

2023-12-07 19:41 UTC, kaloster commented on backend/cellguide/api/v1/upload/actions.py
> +
above is to make sure `dev` bucket is used when running on `rdev` and `local/test`

2023-12-07 21:03 UTC, kaloster commented on backend/layers/thirdparty/s3_provider.py
> +        """
this was added to satiate `mock_s3` during testing - not actually creating any bucket

2023-12-08 17:38 UTC, atarashansky requested changes
Really nice work - a couple of required changes, but otherwise looks good.

2023-12-08 17:38 UTC, atarashansky commented on backend/cellguide/api/v1/upload/actions.py
> +    cell_onthology_id = body["cell_onthology_id"]
`cell_ontology_term_id` is the nomenclature used throughout the portal. let's use it to be consistent

2023-12-08 17:38 UTC, atarashansky commented on backend/cellguide/api/v1/upload/actions.py
> +    bucket_name = f"cellguide-data-public-{env}"
if `rdev`, we need to suffix the bucket with `env-rdev-cellguide/{stack_name}/`. otherwise, all rdevs will be writing to the dev deployment's data

2023-12-08 18:44 UTC, atarashansky approved these changes

2023-12-08 19:40 UTC, merged